### ISSUE TITLE
Scrape parameters do not work

### ISSUE THREAD

**Issue by ShawnHardwick** [WillFantom/overseerr-exporter#7]
The README references the below parameters:

```
overseerr.scrape.genres
overseerr.scrape.companies
```

However, the container does not appear to skip genre or company lookup if setting these to false.

My example docker compose:
```
  overseerr-exporter:
    image: ghcr.io/willfantom/overseerr-exporter:latest
    container_name: overseerr-exporter
    ports:
      - "9850:9850"
    command:
      - "--overseerr.address=http://overseerr:5055"
      - "--overseerr.api-key=${OVERSEERR_API_KEY:?Error}"
      - "--overseerr.scrape.genres=false"
      - "--overseerr.scrape.companies=false"
      - "--log=trace"
```

I noticed this because `overseer-exporter` was taking 12 seconds to respond to a `/metrics` requests from Prometheus. Looking at the trace log, there is a substantial amount of time between retrieving the Overseerr requests and returning the results. 
```
time="2024-06-09T23:08:12Z" level=debug msg="collecting request data..."
time="2024-06-09T23:08:12Z" level=trace msg="fetching request list from overseerr" page=0
time="2024-06-09T23:08:12Z" level=trace msg="fetching user list from overseerr" page=1
time="2024-06-09T23:08:12Z" level=trace msg="fetching user list from overseerr" page=2
time="2024-06-09T23:08:12Z" level=trace msg="fetching request list from overseerr" page=1
time="2024-06-09T23:08:12Z" level=trace msg="fetching user list from overseerr" page=3
time="2024-06-09T23:08:12Z" level=trace msg="fetching request list from overseerr" page=2
time="2024-06-09T23:08:12Z" level=trace msg="fetching user list from overseerr" page=4
time="2024-06-09T23:08:12Z" level=trace msg="fetching request list from overseerr" page=3
time="2024-06-09T23:08:12Z" level=trace msg="fetched all users from overseerr" total_users=10
time="2024-06-09T23:08:12Z" level=debug msg="user data collected" time_elapsed=181.401922ms
time="2024-06-09T23:08:12Z" level=trace msg="fetching request list from overseerr" page=4
time="2024-06-09T23:08:12Z" level=trace msg="fetching request list from overseerr" page=5
time="2024-06-09T23:08:12Z" level=trace msg="fetching request list from overseerr" page=6
time="2024-06-09T23:08:12Z" level=trace msg="fetching request list from overseerr" page=7
time="2024-06-09T23:08:12Z" level=trace msg="fetching request list from overseerr" page=8
time="2024-06-09T23:08:12Z" level=trace msg="fetching request list from overseerr" page=9
time="2024-06-09T23:08:12Z" level=trace msg="fetching request list from overseerr" page=10
time="2024-06-09T23:08:12Z" level=trace msg="fetched all requests from overseerr" total_requests=522
time="2024-06-09T23:08:27Z" level=debug msg="request data collected" time_elapsed=15.19351009s
```

Unfortunately there is no logging in the Go code after the request list retrieval, but looking at the code the only thing that occurs is retrieving the genre/company data using `gooverseerr`. Looking at the code, the parameter is consumed, but there is no conditional to filter genre and company requests if the parameters were set to false.
